import Head from 'next/head';
import React from 'react';
import { Footer, Header } from '../components';

type Props = {
  title: string;
  children: JSX.Element;
};

function Layout({ children, title }: Props) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="xl:max-w-7xl mx-auto p-3">{children}</main>
      {/* <Footer /> */}
    </>
  );
}

export default Layout;
